Repository 3-idiots-team/it-diots, pull requests merged in 2025-03, with the labels that each got.

#2 chore(main): release 1.0.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#10 chore: Github 로그인 추가
  apps/web/app/(feed)/layout.tsx
  apps/web/app/(feed)/page.tsx
  apps/web/app/onboarding/auth/route.ts
  apps/web/app/onboarding/layout.tsx
  apps/web/app/onboarding/page.ts
  apps/web/next.config.mjs
  apps/web/pages/README.md
  apps/web/src/app/auth/handler.ts
  apps/web/src/app/layouts/feed-layout.tsx
  apps/web/src/app/layouts/index.ts
  apps/web/src/app/layouts/onboarding-layout.tsx
  apps/web/src/features/github-login/index.ts
  apps/web/src/features/github-login/ui/index.tsx
  apps/web/src/pages/onboarding/index.ts
  apps/web/src/pages/onboarding/ui/index.tsx
  apps/web/src/shared/actions/index.ts
  apps/web/src/shared/actions/onboarding.ts
  apps/web/src/shared/api/feed.ts
  apps/web/src/shared/api/index.ts
  apps/web/src/widgets/onboarding-form/index.ts
  apps/web/src/widgets/onboarding-form/ui/index.tsx
  packages/shared/src/ui/icon.tsx
  packages/shared/src/ui/index.ts
  packages/supabase/src/types/index.ts
  packages/supabase/src/types/supabase.ts
  turbo.json
Labels: Limit : 1 Day

#17 chore: husky pre-commit 추가
  .husky/pre-commit
  lint-staged.config.js
  package.json
  pnpm-lock.yaml
Labels: Limit : 1 Week

#4 chore(main): release 1.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
